---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template-sample
spec:
  params:
    - name: repo-url
      description: The git repo
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: clone-read
      spec:
        pipelineRef:
          name: clone-read
        params:
          - name: repo-url
            value: $(params.repo-url)
        workspaces:
        - name: shared-data
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-sample
spec:
  params:
    - name: branch
      value: "master"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: event-listener-sample
spec:
  triggers:
    - binding:
        name: trigger-binding-sample
      template:
        name: trigger-template-sample