apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: show-readme
spec:
  description: Read and display README file.
  workspaces:
  - name: source
  steps:
  - name: read
    image: registry.access.redhat.com/rhel7:7.9-1242
    script: | 
      #!/usr/bin/env sh
      cd $(workspaces.source.path)
      pwd
      cat $(workspaces.source.path)/README.md
